spring.application.name=iglesia-api

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/iglesia_db
spring.datasource.username=postgres
spring.datasource.password=alvaro.4658

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Opcional: mostrar parámetros SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Puerto
server.port=8081

# Base 64 key
jwt.secret=OWOvEFjxrgCkhVzpN9Ra5nbmRR+UpZxjNWjvKRtpzDg=
jwt.expiration=3600000


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true